triage:
  label: triage
  dryRun: false

closeAndLock:
  labels:
    - label: "ionitron: support"
      message: >
        Thanks for the issue! This issue appears to be a support request. We use this issue tracker exclusively for
        bug reports and feature requests. Please use our [forum](https://forum.ionicframework.com) or our
        [slack channel](https://ionicworldwide.herokuapp.com/) for questions about the framework or our
        [Stencil slack channel](https://stencil-worldwide.herokuapp.com) for questions about Stencil.


        Thank you for using the Ionic PWA Toolkit!
    - label: "ionitron: missing template"
      message: >
        Thanks for the issue! It appears that you have not filled out the provided issue template. We use this issue
        template in order to gather more information and further assist you. Please create a new issue and ensure the
        template is fully filled out.


        Thank you for using the Ionic PWA Toolkit!
  close: true
  lock: true
  dryRun: false

stale:
  days: 90
  maxIssuesPerRun: 100
  exemptLabels:
    - good first issue
    - triage
  exemptProjects: true
  exemptMilestones: true
  label: "ionitron: stale issue"
  message: >
    Thanks for the issue! This issue is being closed due to inactivity. If this is still
    an issue with the latest version of the Ionic PWA Toolkit, please create a new issue and ensure the
    template is fully filled out.


    Thank you for using Ionic!
  close: true
  lock: true
  dryRun: false

wrongRepo:
  repos:
    - label: "ionitron: ionic"
      repo: ionic
      message: >
        Thanks for the issue! We use this issue tracker exclusively for bug reports and feature requests
        associated with the Ionic PWA Tookit. It appears that this issue is associated with the Ionic Framework.
        I am moving this issue to the Ionic Framework repository. Please track this issue over there.


        Thank you for using the Ionic PWA Toolkit!
    - label: "ionitron: stencil"
      repo: stencil
      message: >
        Thanks for the issue! We use this issue tracker exclusively for bug reports and feature requests
        associated with the Ionic PWA Toolkit. It appears that this issue is associated with Stencil.
        I am moving this issue to the Stencil repository. Please track this issue over there.


        Thank you for using the Ionic PWA Toolkit!
  close: true
  lock: true
  dryRun: false
