/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/redux';
import '@ionic/core';
import 'ionicons';
import {
  Exchange,
  ExchangeId,
} from './services/exchange.service';
import {
  Wallet,
} from './services/wallets.service';
import {
  Currency,
} from './services/currency.service';
import {
  Balance,
} from './services/balance.service';


export namespace Components {

  interface AppExchangebalances {
    'exchangeId': ExchangeId;
  }
  interface AppExchangebalancesAttributes extends StencilHTMLAttributes {
    'exchangeId'?: ExchangeId;
  }

  interface AppExchanges {}
  interface AppExchangesAttributes extends StencilHTMLAttributes {}

  interface AppBarchart {}
  interface AppBarchartAttributes extends StencilHTMLAttributes {}

  interface AppSplinechart {}
  interface AppSplinechartAttributes extends StencilHTMLAttributes {}

  interface AppSunburst {
    'baseCurrency': Currency;
    'exchanges': Exchange[];
    'totalBalance': number;
    'wallets': Wallet[];
  }
  interface AppSunburstAttributes extends StencilHTMLAttributes {
    'baseCurrency'?: Currency;
    'exchanges'?: Exchange[];
    'totalBalance'?: number;
    'wallets'?: Wallet[];
  }

  interface MyApp {}
  interface MyAppAttributes extends StencilHTMLAttributes {}

  interface AppOrder {
    'orderId': string;
  }
  interface AppOrderAttributes extends StencilHTMLAttributes {
    'orderId'?: string;
  }

  interface AppOrders {}
  interface AppOrdersAttributes extends StencilHTMLAttributes {}

  interface AppOverview {}
  interface AppOverviewAttributes extends StencilHTMLAttributes {}

  interface AppPair {
    'exchangeId': ExchangeId;
    'pair': string;
  }
  interface AppPairAttributes extends StencilHTMLAttributes {
    'exchangeId'?: ExchangeId;
    'pair'?: string;
  }

  interface AppPanic {}
  interface AppPanicAttributes extends StencilHTMLAttributes {}

  interface AppSettings {}
  interface AppSettingsAttributes extends StencilHTMLAttributes {}

  interface AppBasecurrency {}
  interface AppBasecurrencyAttributes extends StencilHTMLAttributes {}

  interface AppDust {}
  interface AppDustAttributes extends StencilHTMLAttributes {}

  interface AppEditwallet {
    'walletId': number;
  }
  interface AppEditwalletAttributes extends StencilHTMLAttributes {
    'walletId'?: number;
  }

  interface AppExchangekeys {
    'exchangeId': ExchangeId;
  }
  interface AppExchangekeysAttributes extends StencilHTMLAttributes {
    'exchangeId'?: ExchangeId;
  }

  interface AppHoldings {}
  interface AppHoldingsAttributes extends StencilHTMLAttributes {}

  interface AppKeys {}
  interface AppKeysAttributes extends StencilHTMLAttributes {}

  interface AppPremium {}
  interface AppPremiumAttributes extends StencilHTMLAttributes {}

  interface AppTutorial {}
  interface AppTutorialAttributes extends StencilHTMLAttributes {}

  interface AppBalanceitem {
    'baseCurrency': Currency;
    'cryptodata': Wallet | Balance;
    'exchangeId': ExchangeId;
  }
  interface AppBalanceitemAttributes extends StencilHTMLAttributes {
    'baseCurrency'?: Currency;
    'cryptodata'?: Wallet | Balance;
    'exchangeId'?: ExchangeId;
  }

  interface AppBaseprice {
    'baseCurrency': Currency;
    'btcPrice': number;
  }
  interface AppBasepriceAttributes extends StencilHTMLAttributes {
    'baseCurrency'?: Currency;
    'btcPrice'?: number;
  }

  interface AppCryptoicon {
    'symbol': string;
  }
  interface AppCryptoiconAttributes extends StencilHTMLAttributes {
    'symbol'?: string;
  }

  interface AppExchangeitem {
    'baseCurrency': Currency;
    'exchange': Exchange;
  }
  interface AppExchangeitemAttributes extends StencilHTMLAttributes {
    'baseCurrency'?: Currency;
    'exchange'?: Exchange;
  }

  interface AppOhlc {
    'altPrice': number;
    'curPrice': number;
    'exchangeId': ExchangeId;
    'symbol': string;
  }
  interface AppOhlcAttributes extends StencilHTMLAttributes {
    'altPrice'?: number;
    'curPrice'?: number;
    'exchangeId'?: ExchangeId;
    'symbol'?: string;
  }

  interface AppTrade {}
  interface AppTradeAttributes extends StencilHTMLAttributes {}

  interface AppWallets {}
  interface AppWalletsAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppExchangebalances': Components.AppExchangebalances;
    'AppExchanges': Components.AppExchanges;
    'AppBarchart': Components.AppBarchart;
    'AppSplinechart': Components.AppSplinechart;
    'AppSunburst': Components.AppSunburst;
    'MyApp': Components.MyApp;
    'AppOrder': Components.AppOrder;
    'AppOrders': Components.AppOrders;
    'AppOverview': Components.AppOverview;
    'AppPair': Components.AppPair;
    'AppPanic': Components.AppPanic;
    'AppSettings': Components.AppSettings;
    'AppBasecurrency': Components.AppBasecurrency;
    'AppDust': Components.AppDust;
    'AppEditwallet': Components.AppEditwallet;
    'AppExchangekeys': Components.AppExchangekeys;
    'AppHoldings': Components.AppHoldings;
    'AppKeys': Components.AppKeys;
    'AppPremium': Components.AppPremium;
    'AppTutorial': Components.AppTutorial;
    'AppBalanceitem': Components.AppBalanceitem;
    'AppBaseprice': Components.AppBaseprice;
    'AppCryptoicon': Components.AppCryptoicon;
    'AppExchangeitem': Components.AppExchangeitem;
    'AppOhlc': Components.AppOhlc;
    'AppTrade': Components.AppTrade;
    'AppWallets': Components.AppWallets;
  }

  interface StencilIntrinsicElements {
    'app-exchangebalances': Components.AppExchangebalancesAttributes;
    'app-exchanges': Components.AppExchangesAttributes;
    'app-barchart': Components.AppBarchartAttributes;
    'app-splinechart': Components.AppSplinechartAttributes;
    'app-sunburst': Components.AppSunburstAttributes;
    'my-app': Components.MyAppAttributes;
    'app-order': Components.AppOrderAttributes;
    'app-orders': Components.AppOrdersAttributes;
    'app-overview': Components.AppOverviewAttributes;
    'app-pair': Components.AppPairAttributes;
    'app-panic': Components.AppPanicAttributes;
    'app-settings': Components.AppSettingsAttributes;
    'app-basecurrency': Components.AppBasecurrencyAttributes;
    'app-dust': Components.AppDustAttributes;
    'app-editwallet': Components.AppEditwalletAttributes;
    'app-exchangekeys': Components.AppExchangekeysAttributes;
    'app-holdings': Components.AppHoldingsAttributes;
    'app-keys': Components.AppKeysAttributes;
    'app-premium': Components.AppPremiumAttributes;
    'app-tutorial': Components.AppTutorialAttributes;
    'app-balanceitem': Components.AppBalanceitemAttributes;
    'app-baseprice': Components.AppBasepriceAttributes;
    'app-cryptoicon': Components.AppCryptoiconAttributes;
    'app-exchangeitem': Components.AppExchangeitemAttributes;
    'app-ohlc': Components.AppOhlcAttributes;
    'app-trade': Components.AppTradeAttributes;
    'app-wallets': Components.AppWalletsAttributes;
  }


  interface HTMLAppExchangebalancesElement extends Components.AppExchangebalances, HTMLStencilElement {}
  var HTMLAppExchangebalancesElement: {
    prototype: HTMLAppExchangebalancesElement;
    new (): HTMLAppExchangebalancesElement;
  };

  interface HTMLAppExchangesElement extends Components.AppExchanges, HTMLStencilElement {}
  var HTMLAppExchangesElement: {
    prototype: HTMLAppExchangesElement;
    new (): HTMLAppExchangesElement;
  };

  interface HTMLAppBarchartElement extends Components.AppBarchart, HTMLStencilElement {}
  var HTMLAppBarchartElement: {
    prototype: HTMLAppBarchartElement;
    new (): HTMLAppBarchartElement;
  };

  interface HTMLAppSplinechartElement extends Components.AppSplinechart, HTMLStencilElement {}
  var HTMLAppSplinechartElement: {
    prototype: HTMLAppSplinechartElement;
    new (): HTMLAppSplinechartElement;
  };

  interface HTMLAppSunburstElement extends Components.AppSunburst, HTMLStencilElement {}
  var HTMLAppSunburstElement: {
    prototype: HTMLAppSunburstElement;
    new (): HTMLAppSunburstElement;
  };

  interface HTMLMyAppElement extends Components.MyApp, HTMLStencilElement {}
  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };

  interface HTMLAppOrderElement extends Components.AppOrder, HTMLStencilElement {}
  var HTMLAppOrderElement: {
    prototype: HTMLAppOrderElement;
    new (): HTMLAppOrderElement;
  };

  interface HTMLAppOrdersElement extends Components.AppOrders, HTMLStencilElement {}
  var HTMLAppOrdersElement: {
    prototype: HTMLAppOrdersElement;
    new (): HTMLAppOrdersElement;
  };

  interface HTMLAppOverviewElement extends Components.AppOverview, HTMLStencilElement {}
  var HTMLAppOverviewElement: {
    prototype: HTMLAppOverviewElement;
    new (): HTMLAppOverviewElement;
  };

  interface HTMLAppPairElement extends Components.AppPair, HTMLStencilElement {}
  var HTMLAppPairElement: {
    prototype: HTMLAppPairElement;
    new (): HTMLAppPairElement;
  };

  interface HTMLAppPanicElement extends Components.AppPanic, HTMLStencilElement {}
  var HTMLAppPanicElement: {
    prototype: HTMLAppPanicElement;
    new (): HTMLAppPanicElement;
  };

  interface HTMLAppSettingsElement extends Components.AppSettings, HTMLStencilElement {}
  var HTMLAppSettingsElement: {
    prototype: HTMLAppSettingsElement;
    new (): HTMLAppSettingsElement;
  };

  interface HTMLAppBasecurrencyElement extends Components.AppBasecurrency, HTMLStencilElement {}
  var HTMLAppBasecurrencyElement: {
    prototype: HTMLAppBasecurrencyElement;
    new (): HTMLAppBasecurrencyElement;
  };

  interface HTMLAppDustElement extends Components.AppDust, HTMLStencilElement {}
  var HTMLAppDustElement: {
    prototype: HTMLAppDustElement;
    new (): HTMLAppDustElement;
  };

  interface HTMLAppEditwalletElement extends Components.AppEditwallet, HTMLStencilElement {}
  var HTMLAppEditwalletElement: {
    prototype: HTMLAppEditwalletElement;
    new (): HTMLAppEditwalletElement;
  };

  interface HTMLAppExchangekeysElement extends Components.AppExchangekeys, HTMLStencilElement {}
  var HTMLAppExchangekeysElement: {
    prototype: HTMLAppExchangekeysElement;
    new (): HTMLAppExchangekeysElement;
  };

  interface HTMLAppHoldingsElement extends Components.AppHoldings, HTMLStencilElement {}
  var HTMLAppHoldingsElement: {
    prototype: HTMLAppHoldingsElement;
    new (): HTMLAppHoldingsElement;
  };

  interface HTMLAppKeysElement extends Components.AppKeys, HTMLStencilElement {}
  var HTMLAppKeysElement: {
    prototype: HTMLAppKeysElement;
    new (): HTMLAppKeysElement;
  };

  interface HTMLAppPremiumElement extends Components.AppPremium, HTMLStencilElement {}
  var HTMLAppPremiumElement: {
    prototype: HTMLAppPremiumElement;
    new (): HTMLAppPremiumElement;
  };

  interface HTMLAppTutorialElement extends Components.AppTutorial, HTMLStencilElement {}
  var HTMLAppTutorialElement: {
    prototype: HTMLAppTutorialElement;
    new (): HTMLAppTutorialElement;
  };

  interface HTMLAppBalanceitemElement extends Components.AppBalanceitem, HTMLStencilElement {}
  var HTMLAppBalanceitemElement: {
    prototype: HTMLAppBalanceitemElement;
    new (): HTMLAppBalanceitemElement;
  };

  interface HTMLAppBasepriceElement extends Components.AppBaseprice, HTMLStencilElement {}
  var HTMLAppBasepriceElement: {
    prototype: HTMLAppBasepriceElement;
    new (): HTMLAppBasepriceElement;
  };

  interface HTMLAppCryptoiconElement extends Components.AppCryptoicon, HTMLStencilElement {}
  var HTMLAppCryptoiconElement: {
    prototype: HTMLAppCryptoiconElement;
    new (): HTMLAppCryptoiconElement;
  };

  interface HTMLAppExchangeitemElement extends Components.AppExchangeitem, HTMLStencilElement {}
  var HTMLAppExchangeitemElement: {
    prototype: HTMLAppExchangeitemElement;
    new (): HTMLAppExchangeitemElement;
  };

  interface HTMLAppOhlcElement extends Components.AppOhlc, HTMLStencilElement {}
  var HTMLAppOhlcElement: {
    prototype: HTMLAppOhlcElement;
    new (): HTMLAppOhlcElement;
  };

  interface HTMLAppTradeElement extends Components.AppTrade, HTMLStencilElement {}
  var HTMLAppTradeElement: {
    prototype: HTMLAppTradeElement;
    new (): HTMLAppTradeElement;
  };

  interface HTMLAppWalletsElement extends Components.AppWallets, HTMLStencilElement {}
  var HTMLAppWalletsElement: {
    prototype: HTMLAppWalletsElement;
    new (): HTMLAppWalletsElement;
  };

  interface HTMLElementTagNameMap {
    'app-exchangebalances': HTMLAppExchangebalancesElement
    'app-exchanges': HTMLAppExchangesElement
    'app-barchart': HTMLAppBarchartElement
    'app-splinechart': HTMLAppSplinechartElement
    'app-sunburst': HTMLAppSunburstElement
    'my-app': HTMLMyAppElement
    'app-order': HTMLAppOrderElement
    'app-orders': HTMLAppOrdersElement
    'app-overview': HTMLAppOverviewElement
    'app-pair': HTMLAppPairElement
    'app-panic': HTMLAppPanicElement
    'app-settings': HTMLAppSettingsElement
    'app-basecurrency': HTMLAppBasecurrencyElement
    'app-dust': HTMLAppDustElement
    'app-editwallet': HTMLAppEditwalletElement
    'app-exchangekeys': HTMLAppExchangekeysElement
    'app-holdings': HTMLAppHoldingsElement
    'app-keys': HTMLAppKeysElement
    'app-premium': HTMLAppPremiumElement
    'app-tutorial': HTMLAppTutorialElement
    'app-balanceitem': HTMLAppBalanceitemElement
    'app-baseprice': HTMLAppBasepriceElement
    'app-cryptoicon': HTMLAppCryptoiconElement
    'app-exchangeitem': HTMLAppExchangeitemElement
    'app-ohlc': HTMLAppOhlcElement
    'app-trade': HTMLAppTradeElement
    'app-wallets': HTMLAppWalletsElement
  }

  interface ElementTagNameMap {
    'app-exchangebalances': HTMLAppExchangebalancesElement;
    'app-exchanges': HTMLAppExchangesElement;
    'app-barchart': HTMLAppBarchartElement;
    'app-splinechart': HTMLAppSplinechartElement;
    'app-sunburst': HTMLAppSunburstElement;
    'my-app': HTMLMyAppElement;
    'app-order': HTMLAppOrderElement;
    'app-orders': HTMLAppOrdersElement;
    'app-overview': HTMLAppOverviewElement;
    'app-pair': HTMLAppPairElement;
    'app-panic': HTMLAppPanicElement;
    'app-settings': HTMLAppSettingsElement;
    'app-basecurrency': HTMLAppBasecurrencyElement;
    'app-dust': HTMLAppDustElement;
    'app-editwallet': HTMLAppEditwalletElement;
    'app-exchangekeys': HTMLAppExchangekeysElement;
    'app-holdings': HTMLAppHoldingsElement;
    'app-keys': HTMLAppKeysElement;
    'app-premium': HTMLAppPremiumElement;
    'app-tutorial': HTMLAppTutorialElement;
    'app-balanceitem': HTMLAppBalanceitemElement;
    'app-baseprice': HTMLAppBasepriceElement;
    'app-cryptoicon': HTMLAppCryptoiconElement;
    'app-exchangeitem': HTMLAppExchangeitemElement;
    'app-ohlc': HTMLAppOhlcElement;
    'app-trade': HTMLAppTradeElement;
    'app-wallets': HTMLAppWalletsElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
